[package]
name = "rust_e2ee"
version = "0.1.0"
edition = "2018"

[dependencies]
openssl = "0.10"
rsa = "0.6"
ecdsa = "0.11"
aes = "0.7"
hmac = "0.11"
sha2 = "0.9"
zlib = "0.2"
base64 = "0.13"

[lib]
crate-type = ["cdylib"]
